{
  "formatVersion": "1.1",
  "component": {
    "url": "../../connectycube/2.0.0-beta02/connectycube-2.0.0-beta02.module",
    "group": "com.connectycube.sdk",
    "module": "connectycube",
    "version": "2.0.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.connectycube.org.webrtc",
          "module": "google-webrtc",
          "version": {
            "requires": "1.0.24180"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "connectycube-release.aar",
          "url": "connectycube-android-2.0.0-beta02.aar",
          "size": 1042380,
          "sha512": "2250621634512b12f031990bd286833cf60f90cff9d080e194ab44bafa1db0c035e635eddce879c9e1ab13e91ff439453ccd807e753540635b2126213a3b2e3e",
          "sha256": "df6e474d5a80733ec06af4986233f822072532590802699953f6a44179a4ad1a",
          "sha1": "ecb3a41cfa68efa30521b5b76f207b248f0f4995",
          "md5": "22fd4ee25e69daba62f16c267d1222bc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.connectycube.org.webrtc",
          "module": "google-webrtc",
          "version": {
            "requires": "1.0.24180"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.soywiz.korlibs.krypto",
          "module": "krypto",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.soywiz.korlibs.korio",
          "module": "korio",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.connectycube.tigase.halcyon",
          "module": "halcyon-core",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.soywiz.korlibs.krypto",
              "module": "krypto-jvm"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "connectycube-release.aar",
          "url": "connectycube-android-2.0.0-beta02.aar",
          "size": 1042380,
          "sha512": "2250621634512b12f031990bd286833cf60f90cff9d080e194ab44bafa1db0c035e635eddce879c9e1ab13e91ff439453ccd807e753540635b2126213a3b2e3e",
          "sha256": "df6e474d5a80733ec06af4986233f822072532590802699953f6a44179a4ad1a",
          "sha1": "ecb3a41cfa68efa30521b5b76f207b248f0f4995",
          "md5": "22fd4ee25e69daba62f16c267d1222bc"
        }
      ]
    }
  ]
}
